import assert from 'node:assert/strict';
import worker from '../cloudflare/worker.mjs';
let r=await worker.fetch(new Request('https://test/health'),{});
assert.equal(r.status,200);
assert.equal((await r.json()).trading_enabled,false);
r=await worker.fetch(new Request('https://test/api/orders'),{});
assert.equal(r.status,401);
r=await worker.fetch(new Request('https://test/api/status',{headers:{authorization:'Bearer test'}}),{CONTROL_TOKEN:'test'});
assert.equal(r.status,503);
r=await worker.fetch(new Request('https://test/api/scan',{method:'GET',headers:{authorization:'Bearer test'}}),{CONTROL_TOKEN:'test'});
assert.equal(r.status,405);
r=await worker.fetch(new Request('https://test/api/orders',{headers:{authorization:'Bearer test'}}),{CONTROL_TOKEN:'test',AGENT_URL:'http://vm',AGENT_TOKEN:'test'});
assert.equal(r.status,503);
console.log('5 worker authentication / deployment gate checks passed');
const realFetch=globalThis.fetch;
const authRequest=()=>new Request('https://test/api/futu/preflight',{headers:{authorization:'Bearer test'}});
const secrets={CONTROL_TOKEN:'test',FUTU_CLIENT_ID:'fake',FUTU_REFRESH_TOKEN:'fake'};
let count=0;
globalThis.fetch=async()=>++count===1?new Response(JSON.stringify({access_token:'fake',scope:'quote:read'})):new Response(JSON.stringify({ret_code:0,data:{accounts:[{account_id:'private-id',account_title:'A股模拟账户',market_id:3}]}}));
r=await worker.fetch(authRequest(),secrets);
const connected=await r.json();
assert.equal(connected.a_share_account_present,true);
assert.equal(connected.trading_enabled,false);
assert.equal(JSON.stringify(connected).includes('private-id'),false);
globalThis.fetch=async()=>new Response(JSON.stringify({access_token:'fake',scope:'trade:write'}));
r=await worker.fetch(authRequest(),secrets);
assert.equal(r.status,503);
globalThis.fetch=async()=>{throw new Error('sensitive-token-never-return');};
r=await worker.fetch(authRequest(),secrets);
assert.equal(r.status,502);
assert.equal((await r.text()).includes('sensitive-token'),false);
globalThis.fetch=realFetch;
console.log('3 Futu cloud preflight checks passed');
